### ISSUE TITLE
Coverage not found when testing JS engine

### ISSUE THREAD

**Issue by Qbtly** [NWU-NISL-Fuzzing/COMFUZZ#2]
The paper states that ComFuzz uses coverage as guidance, but I didn’t see ComFuzz using code coverage during runtime when I execute it to test JS compilers. All of the Seed_coverage of Table_Result are 0.00 and all of the Engine_coverage of Table_Testcase are NULL. And the getCove() function related to coverage in the source dose not appear to have been called. Dose ComFuzz use coverage when testing JS engine？If it dose，could you tell me where the specific code is？

**Comment by weucode** [comment]
Thank you very much for your interest in our work! 

We employ [analysisCov1.py](https://github.com/AidPaike/COMFUZZ_Js/blob/7bdd39c38bb028e17c21f4bed1b668825b15301b/workline/analysisCov.py) to get coverage values and clarify which parts of test cases contribute to more coverage. Moreover, the JS module implements multiple interfaces for coverage statistics and merging. One of them only requires calling the coverage testing function in the `muti_harness` function and updating `Engine_coverage`, `Engine_coverage_integration_source`, and `Engine_coverage_integration_all` in `Testcase_Object` through `getCove()`. 

If you still encounter any issues, please stay tuned for future releases. We will continue to maintain this project :)
